// <auto-generated />
using System;
using FinanceEngine.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinanceEngine.Data.Migrations
{
    [DbContext(typeof(FinanceDbContext))]
    [Migration("20251226154956_AddCategoryToEvents")]
    partial class AddCategoryToEvents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("FinanceEngine.Data.Entities.AccountEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("AnnualPercentageRate")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("BalanceTransferFeePercentage")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InitialBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("MinimumPayment")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PaymentDueDateOverride")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PaymentDueDayOfMonth")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("PromotionalAnnualPercentageRate")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PromotionalPeriodEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StatementDateOverride")
                        .HasColumnType("TEXT");

                    b.Property<int?>("StatementDayOfMonth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Type");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("FinanceEngine.Data.Entities.BudgetEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Frequency")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LinkedAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("EffectiveDate");

                    b.HasIndex("IsActive");

                    b.HasIndex("LinkedAccountId");

                    b.ToTable("Budgets");
                });

            modelBuilder.Entity("FinanceEngine.Data.Entities.CategoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Type");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#5C6BC0",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "home",
                            IsActive = true,
                            Name = "Housing",
                            SortOrder = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Color = "#FFA726",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "bolt",
                            IsActive = true,
                            Name = "Utilities",
                            SortOrder = 2,
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            Color = "#26A69A",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "shield",
                            IsActive = true,
                            Name = "Insurance",
                            SortOrder = 3,
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            Color = "#AB47BC",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "subscriptions",
                            IsActive = true,
                            Name = "Subscriptions",
                            SortOrder = 4,
                            Type = 0
                        },
                        new
                        {
                            Id = 5,
                            Color = "#42A5F5",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "wifi",
                            IsActive = true,
                            Name = "Phone & Internet",
                            SortOrder = 5,
                            Type = 0
                        },
                        new
                        {
                            Id = 6,
                            Color = "#66BB6A",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "shopping_cart",
                            IsActive = true,
                            Name = "Groceries",
                            SortOrder = 10,
                            Type = 1
                        },
                        new
                        {
                            Id = 7,
                            Color = "#EF5350",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "restaurant",
                            IsActive = true,
                            Name = "Dining",
                            SortOrder = 11,
                            Type = 1
                        },
                        new
                        {
                            Id = 8,
                            Color = "#78909C",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "directions_car",
                            IsActive = true,
                            Name = "Transportation",
                            SortOrder = 12,
                            Type = 1
                        },
                        new
                        {
                            Id = 9,
                            Color = "#EC407A",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "movie",
                            IsActive = true,
                            Name = "Entertainment",
                            SortOrder = 13,
                            Type = 1
                        },
                        new
                        {
                            Id = 10,
                            Color = "#7E57C2",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "shopping_bag",
                            IsActive = true,
                            Name = "Shopping",
                            SortOrder = 14,
                            Type = 1
                        },
                        new
                        {
                            Id = 11,
                            Color = "#26C6DA",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "fitness_center",
                            IsActive = true,
                            Name = "Health & Fitness",
                            SortOrder = 15,
                            Type = 1
                        },
                        new
                        {
                            Id = 12,
                            Color = "#FFCA28",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "spa",
                            IsActive = true,
                            Name = "Personal Care",
                            SortOrder = 16,
                            Type = 1
                        },
                        new
                        {
                            Id = 13,
                            Color = "#8D6E63",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "school",
                            IsActive = true,
                            Name = "Education",
                            SortOrder = 17,
                            Type = 1
                        },
                        new
                        {
                            Id = 14,
                            Color = "#F48FB1",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "card_giftcard",
                            IsActive = true,
                            Name = "Gifts & Donations",
                            SortOrder = 18,
                            Type = 1
                        },
                        new
                        {
                            Id = 15,
                            Color = "#BDBDBD",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "more_horiz",
                            IsActive = true,
                            Name = "Other",
                            SortOrder = 99,
                            Type = 1
                        });
                });

            modelBuilder.Entity("FinanceEngine.Data.Entities.FinancialEventEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TargetAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Date");

                    b.HasIndex("Status");

                    b.HasIndex("TargetAccountId");

                    b.HasIndex("Type");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("FinanceEngine.Data.Entities.IncomeScheduleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Frequency")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NextPayDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TargetAccountId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TargetAccountId");

                    b.ToTable("IncomeSchedules");
                });

            modelBuilder.Entity("FinanceEngine.Data.Entities.RecurringContributionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Frequency")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NextContributionDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetAccountId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SourceAccountId");

                    b.HasIndex("TargetAccountId");

                    b.ToTable("RecurringContributions");
                });

            modelBuilder.Entity("FinanceEngine.Data.Entities.UserSettingsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("NextPaycheckDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PayFrequency")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PaycheckAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SafetyBuffer")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("FinanceEngine.Data.Entities.BudgetEntity", b =>
                {
                    b.HasOne("FinanceEngine.Data.Entities.CategoryEntity", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinanceEngine.Data.Entities.AccountEntity", "LinkedAccount")
                        .WithMany()
                        .HasForeignKey("LinkedAccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("LinkedAccount");
                });

            modelBuilder.Entity("FinanceEngine.Data.Entities.FinancialEventEntity", b =>
                {
                    b.HasOne("FinanceEngine.Data.Entities.AccountEntity", "Account")
                        .WithMany("Events")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FinanceEngine.Data.Entities.CategoryEntity", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FinanceEngine.Data.Entities.AccountEntity", "TargetAccount")
                        .WithMany()
                        .HasForeignKey("TargetAccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Account");

                    b.Navigation("Category");

                    b.Navigation("TargetAccount");
                });

            modelBuilder.Entity("FinanceEngine.Data.Entities.IncomeScheduleEntity", b =>
                {
                    b.HasOne("FinanceEngine.Data.Entities.AccountEntity", "TargetAccount")
                        .WithMany()
                        .HasForeignKey("TargetAccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TargetAccount");
                });

            modelBuilder.Entity("FinanceEngine.Data.Entities.RecurringContributionEntity", b =>
                {
                    b.HasOne("FinanceEngine.Data.Entities.AccountEntity", "SourceAccount")
                        .WithMany()
                        .HasForeignKey("SourceAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinanceEngine.Data.Entities.AccountEntity", "TargetAccount")
                        .WithMany()
                        .HasForeignKey("TargetAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceAccount");

                    b.Navigation("TargetAccount");
                });

            modelBuilder.Entity("FinanceEngine.Data.Entities.AccountEntity", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
